### ISSUE TITLE
character encoding

### ISSUE THREAD

**Issue by TomOnGit** [python-amazon-mws/python-amazon-mws#100]
I have a character encoding issue with orders.parsed from the orders_api.

print(orders.parsed['Orders']['Order']) shows:
CIUDAD DE MÃ\x89XICO
which should be:
CIUDAD DE MÉXICO

I'm using Python 3.6.5 on MacOS Mojave

**Comment by jameshiew** [comment]
I don't have access to an Amazon MWS account at the moment, but this issue looks similar to https://github.com/python-amazon-mws/python-amazon-mws/issues/30

**Comment by elcolumbio** [comment]
That issue a lot of people from europe run into, me too.
I tried to solve it by design in my pull request 75.
Because there is no reason a user should run into this issue.
We should hide the bytes response as good as possible and offer strings.

1. principled by design it should be the first thing our api does, before processing the data further
2. we can implement the best practise to get an encoding (it's none trivial and there are a couple of options which are obvious but sometimse wrong, like response header, or default encoding)

**Comment by GriceTurrble** [comment]
My apologies for lack of response, personal and work life have been a bit hectic.

I am slowly running tests on #75 to see how it compares to existing state of `develop` version. I'm aware we have issues such as encoding especially in `master` version which is quite out of date, and similar issues may be present on `develop`.

Once that PR is cleared up - and that will be a relatively major upgrade for the core code as it is - I will be working on tidying up for a major release, after which we'll work on some faster iterations for bug fixes, especially encoding issues like this one.

**Comment by TomOnGit** [comment]
I'd love to test it and am happy to help, but I'm not an experienced developer honestly not sure how to. First I've installed pythhon-amazon-mws via `pip install mws` in a virtualenv virtual environment, so I'm not entirely sure how to use git in that situation. Secondly I'm not sure how to use a pull request.

**Comment by elcolumbio** [comment]
You should be able to learn the basics of git, you are already asking good questions.
It's time well spent.

**Comment by jameshiew** [comment]
@TomOnGit, a quickstart might be like
```
git clone https://github.com/python-amazon-mws/python-amazon-mws.git
cd python-amazon-mws/
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip setuptools wheel
pip install -r requirements.txt
pip install -e .
```
You can then make changes to the code as normal and they will be reflected in the `venv` virtual environment you've made. You will need to clone your own fork of the repo if you want to open pull requests to contribute your code.

Does anyone have an example of a response body which triggers this decoding error, as a Python string (redacted as necessary)? We could potentially use this as part of an automated test to verify any fix.

**Comment by elcolumbio** [comment]
I already made up some tests for encoding and xml to json.
But would be nice if we have more data to test.
https://github.com/innotrade24/python-amazon-mws1/blob/d37de8cdabf64a134d47183290bae79dae1cf6cf/tests/test_wrappers.py#L35-L43

**Comment by TomOnGit** [comment]
> @TomOnGit, a quickstart might be like
> 
> ```
> git clone https://github.com/python-amazon-mws/python-amazon-mws.git
> cd python-amazon-mws/
> python3 -m venv venv
> source venv/bin/activate
> pip install --upgrade pip setuptools wheel
> pip install -r requirements.txt
> pip install -e .
> ```
> You can then make changes to the code as normal and they will be reflected in the `venv` virtual environment you've made. You will need to clone your own fork of the repo if you want to open pull requests to contribute your code.
> 
> Does anyone have an example of a response body which triggers this decoding error, as a Python string (redacted as necessary)? We could potentially use this as part of an automated test to verify any fix.

Thanks for explaining. It's not clear to me yet though, as I know how to clone a repository and setup a virtual environment, but what I don't fully understand is how I work with a pull request in the project that I'm using the package in as the code is in /project/venv/lib/python3.6/site-packages/mws. Or should I clone the pull request to a different folder and manually move that code to  /project/venv/lib/python3.6/site-packages/mws?

I'm getting another (or maybe 2) errors now actually:
  File "app_data_mws_reports.py", line 170, in get_mws_report
    data_raw = reports_api.get_report(report_id)
  File "/home/ss7wsa/Git/fbaws/venv/lib/python3.6/site-packages/mws/mws.py", line 437, in get_report
    return self.make_request(data)
  File "/home/ss7wsa/Git/fbaws/venv/lib/python3.6/site-packages/mws/mws.py", line 271, in make_request
    parsed_response = DataWrapper(data, response.headers)
  File "/home/ss7wsa/Git/fbaws/venv/lib/python3.6/site-packages/mws/mws.py", line 134, in __init__
    raise MWSError("Wrong Contentlength, maybe amazon error...")
mws.mws.MWSError: Wrong Contentlength, maybe amazon error...
^CException ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

**Comment by jameshiew** [comment]
Apologies for the delay in getting back, if you want to test your local version of `mws` with your project - you should be able to do something like `pip uninstall mws && pip install -e /home/tom/python-amazon-mws` while you are inside the venv which your project is using (assuming your local version of `mws` lives at `/home/tom/python-amazon-mws`). Your project's venv will then use a 'live' version of whatever is checked out at `/home/tom/python-amazon-mws`, rather than `mws` from PyPI. You can then just make changes in `/home/tom/python-amazon-mws` and shouldn't have to worry about looking inside the `/project/venv/` folder or anything like that.

For further discussion on the encoding issue, let's consolidate in issue #30
