### ISSUE TITLE
submitting flat file in .xlsm format via submit_feet()

### ISSUE THREAD

**Issue by btcorgtfo** [python-amazon-mws/python-amazon-mws#138]
hi,

I'd like to submit a flat file to update an existing product in my seller central account.

1. Any idea which is the correct feed?
_POST_FLAT_FILE_LISTINGS_DATA_ or _POST_FLAT_FILE_INVLOADER_DATA_

2. If i try to submit i get the error
TypeError: Unicode-objects must be encoded before hashing

As feed=.. is use the path as a string.

best regards

**Comment by btcorgtfo** [comment]
i m able to update something after opening the file via open("flatfile.txt",'r').read().encode('utf-8'), where the .txt is a tsv
however, amazon doesn't like it and complains "The file has an incorrect template type. To correct this error, download the correct template from seller Help." And ideas?

**Comment by btcorgtfo** [comment]
so, it seems to works if I use "_POST_FLAT_FILE_LISTINGS_DATA_" instead of "_POST_FLAT_FILE_INVLOADER_DATA_" alltough the api docu says "To create a listing for a product not yet in the Amazon catalog," which is not the case here

**Comment by elcolumbio** [comment]
Since i looked into it i can add.
It seems totally fine to use "POST_FLAT_FILE_LISTINGS_DATA". In the second line it says you can use it for updating listings.
The templates for the different feeds you mentioned are different. I downloaded them both and found for example different key names like 'item-condition' vs 'condition-type'. True that its confusing since it differs from the manual upload in the seller central.
