### ISSUE TITLE
how to parser the xml file 

### ISSUE THREAD

**Issue by didierzhu** [python-amazon-mws/python-amazon-mws#158]
Hi,
I am a beginner,I try to print the order information to csv, I have a question on how to parser the xml file.
import mws.mws
import xml.etree.ElementTree as ET
from lxml import etree
.....
orders_api = mws.Orders(access_key,secret_key,account_id,region)
orders = orders_api.list_orders(marketplaceids=MarketplaceID,created_after='2020-02-23')
xml_file = orders.original
root = ET.fromstring(xml_file)
ns = xml.nsmap[None]
ns = '{%s}' % ns
for item in xml.findall("{0}ListOrderResult/{0}Orders/{0}Order".format(ns)):
    print(item)

**Comment by GriceTurrble** [comment]
Automatic parsing is included. You should find what you need accessible as attributes, starting from `orders.parsed` (instead of `orders.original`).

Note that the parser will see the first node, `Orders`, as a single entry, even though it ought to be the list of Order objects. The next node down, `Order`, will end up as the list you want to iterate.

Please try the following:

```python
response = orders_api.list_orders(...)
for order in response.parsed.Orders.Order:
    print(order.AmazonOrderId)
    print(order.PurchaseDate)
    print(order.LastUpdateDate)
    # and so on.
```

See the example response [here](https://docs.developer.amazonservices.com/en_US/orders-2013-09-01/Orders_ListOrders.html) for the set of data you can expect in your responses. I recommend you try your request in the interactive shell and play around with the response object and the nodes available in `.parsed` to get the data you're looking for.

**Comment by didierzhu** [comment]
Thank you very much @GriceTurrble , you really give me a new way. 
Can I know how you can use the mothode .parsed.Order.Order, because the class below?

class DictWrapper(object):
    def __init__(self,xml,rootkey=None):
        self.original = xml
        self.response = None
        self._rootkey = rootkey
        ......
@property
def parsed(self):
    if self._rootkey:
        return self._response_dict.get(self._rootkey)
        return self._response_dict

How can I know rootkey means? Beause there are also <ListOrderResponse> and <listOrderResult>.

Thanks in advance

**Comment by Bobspadger** [comment]
You don't need to be using it explicitly. This builds the response for you from the xml Amazon return

so as an overview (pseudocode)

```python
api = products_api()
my_product = products_api.get(product_id)

my_product.parsed 
```

This will output the dict like object that has transformed the amazon XML into nice dict like access for you.
