### ISSUE TITLE
requests.exceptions.SSLError: HTTPSConnectionPool

### ISSUE THREAD

**Issue by posidonius** [python-amazon-mws/python-amazon-mws#161]
Did Amazon MWS recently change policy regarding SSL? Maybe in February? Software I've written basically broke around Feb 20 or Feb 21. Just debugging now and I see an SSL error.

`requests.exceptions.SSLError: HTTPSConnectionPool`
`Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")`

I did some searching around to see if Amazon published news about SSL authentication and haven't found any references to a change.

**Comment by GriceTurrble** [comment]
As stated in the Slack convo we're having, this appears to be in your local setup and how `requests` is interacting with the SSL module in your OS. Neither Amazon nor `python-amazon-mws` appear to be involved.

See: https://stackoverflow.com/questions/54135206/requests-caused-by-sslerrorcant-connect-to-https-url-because-the-ssl-module
