### ISSUE TITLE
Encoding issue with API: list_order_items

### ISSUE THREAD

**Issue by Dan-Stephen** [python-amazon-mws/python-amazon-mws#163]
I'm developing an app interacting with Amazon Japan site.(Using lib mws 0.8.7) 

Through the logs for import order data I found that the data type returned by this API is DictWrapper, but some of the fields (for example, 'OrderItems' ->'OrderItem'->'Title'->'value') get garbled characters(like 'ã\x80\x8c3æ\x9e\x9aå\x85¥ã\x82\x8aã\x80\x8dNintendo Switch ä¿\x9dè\xad·ã').
It looks like decoding is missed before packaging special fields data into a DictWrapper model.

Same problem happens in other places like calling API list_orders.

Kindly please advice how can I proceed. Thanks!

**Comment by btcorgtfo** [comment]
hi, not exactly the same but I have faced the issue with EU Marketplaces and `get_matching_product()`

I have solved this via

`result.parsed.encode('ISO-8859-1').decode()`

**Comment by Amedeo91** [comment]
I think this will fix it: https://github.com/python-amazon-mws/python-amazon-mws/pull/168

**Comment by Amedeo91** [comment]
> hi, not exactly the same but I have faced the issue with EU Marketplaces and `get_matching_product()`
> 
> I have solved this via
> 
> `result.parsed.encode('ISO-8859-1').decode()`

I do not like it. It means that you need to convert to string and then back to dictionary the parse response.

**Comment by btcorgtfo** [comment]
you do it only on the field you are interested, e.g. asin title but using the output directly would be my preferred solution

**Comment by Amedeo91** [comment]
No at all, the response for requests is a byte string and I am converting into a char string. This is the XML from Amazon. By correcting parsing it into utf-8, then the special chars are correctly parsed.
Not entirely sure about the Chinese one

**Comment by urrpurr** [comment]
I've encountered this encoding issue with list_order_items and also with list_orders. I always get incorrect and weird text when exporting orders from the German amazon (they have a lot of special characters). 

I tried debugging why this was happening and it seems like at one point mws handles the response as a bytestring (response.context being used in mws.py) but then that is passed to a dictwrapper and finally when I parse the result it is treated as a str instead of a bytestring.

I managed to fix this on my end by changing the following line in mws.py:
`data = response.content`
to:
`data = response.content.decode('utf8')`

**Comment by GriceTurrble** [comment]
Hi folks,

Checking in here with an update. Recent changes in `develop` branch have included an encoding change for the XML response content. Amazon states that their responses are encoded in ISO-8859-1 (or Latin-1), so we are now explicitly using that encoding type. If the decode call fails for any reason, response content should now be raised within an `MWSError` exception:

https://github.com/python-amazon-mws/python-amazon-mws/blob/3e8f3de1105fb272935f81e452ee5e136024fe21/mws/mws.py#L136,L144

I advise pulling latest from `develop` and seeing if that resolves your issue. If not, please let us know.
