### ISSUE TITLE
Can't check inventory of UK

### ISSUE THREAD

**Issue by AntoWkill** [python-amazon-mws/python-amazon-mws#262]
Hello Mws.inventory seems don't have a Uk inventory (after brexit is not same of EU inventory fba)

**Comment by GriceTurrble** [comment]
We rely on MWS docs for the endpoints and marketplace IDs. According to them, the MWS endpoint is still "eu", but specifying the marketplace by the UK or GB marketplace_id *should* show relevant info.

Source: https://docs.developer.amazonservices.com/en_US/dev_guide/DG_Endpoints.html

Of course we got word that was updating for the PL market even before the docs got updated. So, have you seen news of a new endpoint to point to for UK?

**Comment by AntoWkill** [comment]
The main problem is that amz.inventory doesn't support marketplace_id, only Domain and Region.

```
  x = mws.Inventory(access_key=access_key, secret_key=secret_key, account_id=seller_id, domain='https://mws-eu.amazonservices.com', region="GB",auth_token='XXXX', marketplace_id='A1F83G8C2ARO7P')

TypeError: __init__() got an unexpected keyword argument 'marketplace_id'
```

**Comment by GriceTurrble** [comment]
Correct, the API subclass does not take `marketplace_id`. Some request methods do, however.

For instance, `Inventory.list_inventory_supply` accepts a `marketplace_id` argument:

https://github.com/python-amazon-mws/python-amazon-mws/blob/a22942719871eb8a2a57e9ef56654f4bafe73f7b/mws/apis/inventory.py#L23-L30

This matches the signature of the request in MWS: https://docs.developer.amazonservices.com/en_US/fba_inventory/FBAInventory_ListInventorySupply.html

Getting started with this API, you would simply set up an API instance with the correct `region` like so:

```python
inventory_api = mws.Inventory(
    access_key=access_key,
    secret_key=secret_key,
    account_id=seller_id,
    auth_token=auth_token,
    region="GB",  # or "UK" as an alias
)
```

Beyond that, it appears that Amazon still uses the `mws-eu.amazonservices.com` endpoint for the UK market. That may not make sense - one might expect a `mws.amazonservices.co.uk` endpoint for UK specifically - but nothing really stops them from doing so, as far as I'm aware. For that matter, if they wanted to just use `mws.amazonservices.com` as an endpoint for every region, they very well could.

Point is, this is not something we can control. If Amazon has changed up their endpoints and there's documentation showing that distinction, we'll be happy to make changes to reflect them.

If you're experiencing some sort of downtime due to that type of change, you can always adjust the endpoint manually as a stopgap solution by assigning it to `.domain` like so:

```python
inventory_api = mws.Inventory(...)
inventory_api.domain = "https://www.example.com"
```

**Comment by AntoWkill** [comment]
I tried to add the "GB" or "UK" region but api give me also the paneuropean (so all europe excluding UK) value of inventory.

**Comment by GriceTurrble** [comment]
As before, this is on Amazon to correct. They've decided to leave the UK region in their EU API section, so we can't affect that from our side.

**Comment by AntoWkill** [comment]
So there is any way to get the inventory of uk by api?

**Comment by GriceTurrble** [comment]
I would guess that it's mixed in with the EU inventory. Either that or you specify the UK marketplace on specific requests that take `marketplace_id` parameters.

**Comment by AntoWkill** [comment]
If i specify marketplace_id on list_inventory_supply have the error: 

`Traceback (most recent call last):
  File "inventoryUK.py", line 31, in <module>
    report = x.list_inventory_supply(skus=asins, marketplace_id=A1F83G8C2ARO7P)
NameError: name 'A1F83G8C2ARO7P' is not defined`

Also i put the marketplace id into a variable.

**Comment by GriceTurrble** [comment]
>     report = x.list_inventory_supply(skus=asins, marketplace_id=A1F83G8C2ARO7P)
> NameError: name 'A1F83G8C2ARO7P' is not defined`

This error is due to the ID not being a string. You need to use quotes around it: `'A1F83G8C2ARO7P'`.

**Comment by AntoWkill** [comment]
Already tried

Error:

`Traceback (most recent call last):
  File "inventoryUK.py", line 32, in <module>
    report = x.list_inventory_supply(skus=asins, marketplace_id='A1F83G8C2ARO7P')
  File "/usr/local/lib/python3.8/dist-packages/mws/utils.py", line 250, in _wrapped_func
    return request_func(self, *args, **kwargs)
TypeError: list_inventory_supply() got an unexpected keyword argument 'marketplace_id'`

**Comment by GriceTurrble** [comment]
You must be on the 0.8 version, then. I don't see that parameter in master branch, but latest code in develop branch does have that argument.

I can issue a patch for that on 0.8 version to fill in the gap a bit. Will work on that later today.

**Comment by AntoWkill** [comment]
Thank you! :)

**Comment by AntoWkill** [comment]
Hello after your changes work UK! but now the xml arrive not like xml

"b'<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">\n  <ListInventorySupplyResult>\n    <MarketplaceId>XXX</MarketplaceId>\n    <InventorySupplyList>\n      <member>\n        <Condition>XXX</Condition>\n        <SupplyDetail/>\n        <TotalSupplyQuantity>XXX</TotalSupplyQuantity>\n        <FNSKU>B07FPT6CNR</FNSKU>\n      "

**Comment by AntoWkill** [comment]
all the XML are with this "b" starting now

**Comment by Bobspadger** [comment]
you should be using the `.parsed` method to retrieve the `dict` like representation of the result.

You are most likely looking at the original bytes data returned 'over the wire' from the request.

MWS turns the XML into native python data structures.

**Comment by GriceTurrble** [comment]
Release completed for 0.8.15 which includes a fix for this.
