### ISSUE TITLE
Question/Problem with certain characters

### ISSUE THREAD

**Issue by dfrdmn** [python-amazon-mws/python-amazon-mws#30]
First, thanks for the work and updates to the original.

I just updated from python 2.7 to 3.6 and am (not surprisingly) running into some string errors. When executing `get_matching_product_for_id`, we have a number of products that should return accented characters such as: `'Publisher': {'value': 'Bärenreiter'}`; however we are currently getting `'Publisher': {'value': 'BÃ¤renreiter'}`.

From the interpreter, I see the following:
* `response.parsed` returns `'Publisher': {'value': 'BÃ¤renreiter'}`
* `response.original` returns `<ns2:Publisher>BÃ¤renreiter</ns2:Publisher>`
* `response.response.text` returns `<ns2:Publisher>BÃ¤renreiter</ns2:Publisher>`
* `response.response.content` returns `<ns2:Publisher>B\xc3\xa4renreiter</ns2:Publisher>` (now we're getting somewhere!)
* `response.response.content.decode('utf-8')` returns `<ns2:Publisher>Bärenreiter</ns2:Publisher>`

It looks like requests is interpreting the encoding incorrectly which is validated by seeing that  `response.response.encoding` is set to `'ISO-8859-1'`.

I'm pretty naive when it comes to encodings, so this may be a problem with my setup. However, since Amazon states that this XML will always be UTF-8, would it makes sense to do `data = response.content.decode('utf-8')` in [L209](https://github.com/jameshiew/python-amazon-mws/blob/e7fdc9463e9e42122707c48fc55e34097ed65e8a/mws/mws.py#L209) of mws.py?

**Comment by jameshiew** [comment]
Hey @dfrdmn , thanks for bringing this issue to light in detail!

The corresponding line in upstream is https://github.com/czpython/python-amazon-mws/blob/master/mws/mws.py#L199 which is also `data = response.content` - I'd suggest this isn't changed so that things keep working as is, for people who are using Python 2.7 and switch from the upstream library to this one - but definitely somewhere it should be noted that the response content needs to be explicitly decoded to UTF-8 in Python 3.x

I'm not too familiar with encodings either - in my experience Amazon seems to use or expect ISO-8859-1 in a lot of places, at least that's been my experience with .csv uploads. Not sure where that `request.response.encoding` is set to 'ISO-8859-1' - I'm guessing Amazon is setting it directly on the response for some reason. I'll leave this issue open until there is proper documentation set up for people using Python 3.x re. this encoding issue.

Also this closed issue might be relevant https://github.com/jameshiew/python-amazon-mws/issues/28 - they seem to have had a similar problem.

**Comment by GriceTurrble** [comment]
It appears the use of ISO-8859-1 is to be expected: https://docs.developer.amazonservices.com/en_US/dev_guide/DG_ISO8859.html

> Amazon Marketplace Web Service (Amazon MWS) uses character encoding based on ISO 8859-1.

Perhaps run a version check for 2.x and leave as-is, otherwise automatically encode response data as UTF-8?

**Comment by dfrdmn** [comment]
Ah, good find. I've done a couple of simple tests on my end, and it seems like it might be as simple as:

```
import six

if six.PY2:
    data = response.content
else:
    data = response.content.decode()
```

**Comment by jameshiew** [comment]
That Python version check looks like a good solution - I will think how to implement this change in a non-breaking way for people who are already using Python 3 and have figured out the fix themselves. We might be able to do this with a major version upgrade (0.8.x) or some flag, to automatically `decode()` the data where needed, keeping in mind `response.content` is sometimes a feed/binary data (from what I can remember - I have to admit I haven't had to use the library all that much recently).

I've been playing around with Python 3 and `get_matching_product_for_id` on the DE marketplace and haven't encountered the decoding issue for some reason - it decoded OK the first time, so will keep experimenting.

**Comment by dfrdmn** [comment]
It's a start. However, yesterday I ran into a situation where, under Python 3, `.decode()` failed and I needed to do `.decode('latin-1')` which I got to by checking for a UnicodeDecode error. I'm going to look into what comes back in a little more detail and see if we can be smarter. It feels like an `if` followed by a `try` is a bit hacky. I'll try to play with it today and see if I can be a little more concrete.

**Comment by wernight** [comment]
What about using response.text like on https://github.com/czpython/python-amazon-mws/pull/25?

**Comment by elcolumbio** [comment]
This should fix it
https://github.com/innotrade24/python-amazon-mws1/blob/5622c36b4aa54bc81aa8697e443de0b695530a94/mws/mws.py#L119-L120

**Comment by GriceTurrble** [comment]
As mentioned above, #75 may handle this bug naturally, so we'll keep track of this issue as part of our 1.0 release plan.

**Comment by elcolumbio** [comment]
I try to improve the auto detection of how to decode the bytes object.

Actually chardet is not always right. Because it's impossible to guess every encoding.
So if there is for example no bulletpoint in the request.response byte object it harder to detect.

often you have only one row with one non ascii character.
I did parse per row and just added the confidence (1 = 100 %)
Ascii is always 100% since those rows are pure ascii.
                        
| encoding |	confidence |
| ---------------- | --------------- |
| ISO-8859-1 | 0.578218 |
| ascii | 9457.000000 |

the actual row is:
b'              <ProductDescription> Verst\xc3\xa4rker gps</ProductDescription>'
\xc3\xa4 stands in utf-8 for ä
but in ISO-8859-1 for the two character Ã and ¤
So it's utf8 not ISO-8859-1. The confidence level for the complete bytes object is low, like 70%.
That's good we should be able to hack something together, like one simple fact we know.

**Comment by elcolumbio** [comment]
That's a [known issue](https://github.com/chardet/chardet/issues/138) of the chardet library.

**Comment by elcolumbio** [comment]
Without knowing what's going on. It probably gives the sum, or however it aggregates the probability of the two characters Ã and ¤. A higher probability then the single probability of ä.
That effect would disappear for one more none ASCII letter.

**Comment by GriceTurrble** [comment]
Hi folks,

Checking in here with an update. Recent changes in `develop` branch have included an encoding change for the XML response content. Amazon states that their responses are encoded in ISO-8859-1 (or Latin-1), so we are now explicitly using that encoding type. If the decode call fails for any reason, response content should now be raised within an `MWSError` exception:

https://github.com/python-amazon-mws/python-amazon-mws/blob/3e8f3de1105fb272935f81e452ee5e136024fe21/mws/mws.py#L136,L144

I advise pulling latest from `develop` and seeing if that resolves your issue. If not, please let us know.

Closing this issue as it has been sitting unresolved for quite some time, and hopefully the above change fixes it. If not, please open a new issue. Thank you.
