### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by JasonCrowe** [python-amazon-mws/python-amazon-mws#35]
Can anyone share some sample code that works? The docs don't really help with getting started & I would like to give this a go. :)

I would be happy to submit a PR to update the docs once I get things working.

**Comment by GriceTurrble** [comment]
Though sparse, the [README's Quickstart section](https://github.com/jameshiew/python-amazon-mws#quickstart) is not too far off the mark. Response content is turned into a `DictWrapper` instance that can be accessed either as a dict or as an object with attributes.

That said, let's expand on that here, shall we? :)

## Simple Example: service status
With the example from the QuickStart section, we can get the [service status for the Orders API](http://docs.developer.amazonservices.com/en_US/orders-2013-09-01/MWS_GetServiceStatus.html) like so:

    import mws, os

    # set up our API instance using MWS credentials (as environment variables)
    orders_api = mws.Orders(
        access_key=os.environ['MWS_ACCESS_KEY'],
        secret_key=os.environ['MWS_SECRET_KEY'],
        account_id=os.environ['MWS_ACCOUNT_ID'],
    )

    # make the call
    response = orders_api.get_service_status()

`response` is a DictWrapper instance with a few main attributes:

* `response.original`: the original XML response data stored as a string. If you want to parse the XML on your own, you can do so from here.
* `response.response`: may seem redundant, but actually this is the HTTP response code for the request (usually 200). You can test here for an error (*I have modified code elsewhere with an `is_error` flag; this may be added in future*).
* `response.parsed`: this is where the fun begins. This is an ObjectDict (defined in `mws.utils`), which is an extension of the built-in `dict` class. Each key of this dict can be accessed using an attribute of the same name as that key for convenience (key index syntax (`['']`) is not required).

### Using `.parsed`
From the above example, the content of `.parsed` reads like a dict:

    >>> response.parsed
    {'value': '\n    ', 'Status': {'value': 'GREEN'}, 'Timestamp': {'value': '2017-06-14T16:39:12.765Z'}}

Any of the keys of that dict can be accessed as an attribute:

    >>> response.parsed.Status
    'GREEN'
    >>> response.parsed.Timestamp
    '2017-06-14T16:39:12.765Z'

All XML nodes from the parsed data are accessed in the same way. Accessing a node with nothing but a value will return that value, while accessing a node that has child nodes will return a new ObjectDict.

#### Optional: Accessing Values As Dict Keys
Optionally, you can access a node like a dict using key index syntax. Be warned, this will default to an ObjectDict, rather than shortcutting to the value at that node:

    >>> response.parsed['Status']
    {'value': 'GREEN'}
    >>> response.parsed.get('Status')
    {'value': 'GREEN'}
    >>> type(response.parsed['Status'])
    <class 'mws.utils.ObjectDict'>

To account for this, if you access a node with data using a dict key or `.get()`, you must access its `value` attribute manually:

    >>> response.parsed['Status'].value
    'GREEN'
    >>> response.parsed['Status']['value']
    'GREEN'

This is, admittedly, not very intuitive. We'll look to adjust this in the future, I reckon. For the time being, this workaround is required if you need to test a node's presence using `.get()`, for instance.

## Longer Example: Orders.list_order_items
*Note: I cannot run this code myself, as I do not have an Amazon Seller account.*

Given an example response from [Amazon MWS Documentation](http://docs.developer.amazonservices.com/en_US/orders-2013-09-01/Orders_ListOrderItems.html) for this call, your `reponse.parsed` may look like so (*generated manually by copying the text in example response and creating a `DictWrapper`*):

    {
        'NextToken': {'value': 'MRgZW55IGNhcm5hbCBwbGVhc3VyZS6='}, 
        'AmazonOrderId': {'value': '058-1233752-8214740'}, 
        'OrderItems': {
            'OrderItem': [
                {
                    'ASIN': {'value': 'BT0093TELA'}, 
                    'OrderItemId': {'value': '68828574383266'}, 
                    'BuyerCustomizedInfo': {
                        'CustomizedURL': {'value': 'https://zme-caps.amazon.com/t/bR6qHkzSOxuB/J8nbWhze0Bd3DkajkOdY-XQbWkFralegp2sr_QZiKEE/1'}
                    }, 
                    'SellerSKU': {'value': 'CBA_OTF_1'}, 
                    'Title': {'value': 'Example item name'}, 
                    'QuantityOrdered': {'value': '1'}, 
                    'QuantityShipped': {'value': '1'}, 
                    'ProductInfo': {
                        'NumberOfItems': {'value': '12'}
                    }, 
                    'PointsGranted': {
                        'PointsNumber': {'value': '10'}, 
                        'PointsMonetaryValue': {
                            'CurrencyCode': {'value': 'JPY'}, 
                            'Amount': {'value': '10.00'}
                        }
                    }, 
                    'ItemPrice': {
                        'CurrencyCode': {'value': 'JPY'}, 
                        'Amount': {'value': '25.99'}
                    }, 
                    'ShippingPrice': {
                        'CurrencyCode': {'value': 'JPY'}, 
                        'Amount': {'value': '1.26'}
                    }, 
                    'ScheduledDeliveryEndDate': {'value': '2013-09-09T01:30:00.000-06:00 '}, 
                    'ScheduledDeliveryStartDate': {'value': '2013-09-071T02:00:00.000-06:00 '}, 
                    'CODFee': {
                        'CurrencyCode': {'value': 'JPY'}, 
                        'Amount': {'value': '10.00'}
                    }, 
                    'CODFeeDiscount': {
                        'CurrencyCode': {'value': 'JPY'}, 
                        'Amount': {'value': '1.00'}
                    }, 
                    'GiftMessageText': {'value': 'For you!'}, 
                    'GiftWrapPrice': {
                        'CurrencyCode': {'value': 'JPY'}, 
                        'Amount': {'value': '1.99'}
                    }, 
                    'GiftWrapLevel': {'value': 'Classic'}, 
                    'PriceDesignation': {'value': 'BusinessPrice'}
                },
                ... # more OrderItem objects
            ]
        }
    }

Some notes first:

* **List Location**: The XML for this example contains many **&lt;OrderItem&gt;** tags within the **&lt;OrderItems&gt;** tag, which is expected: this is the set of OrderItem objects to work on. In our parsed response, when many tags of the same name are all children of the same parent node, they will be made into a list of ObjectDicts that can be accessed from the same key they all share. In the example, `OrderItems.OrderItem` is that list.
  * It may seem more intuitive to have a structure like `{'OrderItems': [...]}` instead of `{'OrderItems': {'OrderItem': [...]}]}`, but that would mean removing an expected key from the parsed response data. Further, some responses may have other keys at the same node level, so we must ensure that each is captured correctly.
  * **Single-Item Responses**: Some responses of this type may only contain a single "item". We don't have intelligent behavior for this scenario, so instead of a list with a single element, you will just find a single ObjectDict at that node. The simplest way to work around this at the moment is to test the node with `isinstance(response.parsed.OrderItems.OrderItem, list)` and handle it accordingly. (*in the future, we may allow every node to be iterable so that this check is not necessary.*)
* The actual output may show various `'value'` keys with empty string values, or strings containing only spaces. In the above example, I've removed these lines to save space. These can be safely ignored (we will remove these "empty" values later).

Given this example, suppose you want to get the **ItemPrice** for the first item in this order. MWS typically returns prices with two attributes, **Amount** and **CurrencyCode**, so that you can process the price in whatever currency you need.

So, to get these two values, we might do this:

    >>> response.parsed.OrderItems.OrderItem[0].ItemPrice.Amount
    '25.99'
    >>> response.parsed.OrderItems.OrderItem[0].ItemPrice.CurrencyCode
    'JPY'

Note that all data is returned as a string. To parse this, you may want to pass **ItemPrice.Amount** through `float`, [`decimal.Decimal`](https://docs.python.org/3.5/library/decimal.html), or [`fractions.Fraction`](https://docs.python.org/3.5/library/fractions.html), as you see fit.

Also note how long these calls can be. A good practice is to work on parts of the response at a time by assigning them to a new variable or passing them to your own parsing method, depending on your needs:

    >>> items = response.parsed.OrderItems.OrderItem # see note above about List Location
    >>> item_0 = items[0] # or iterate as needed; see note above about Single-Item Responses
    >>> item_0.ItemPrice.Amount
    '25.99'
    >>> item_0.ItemPrice.CurrencyCode
    'JPY'

## Moving Forward
This module is mostly designed as an intermediary and not as a full-fledged solution, so you will need to follow [Amazon MWS documentation] to see which calls you need to make and what they do. From there, check the `mws` module to ensure it covers the same method(s) you need and what they are called, how those methods accept the data required, etc.

You will then need to spend some time playing around with those methods with some test cases using your own MWS credentials, particularly in the Python interactive shell. We cannot guarantee what the response content will be for any given call, nor that it will even be the same from one call to the next: you must get some sample data from the responses to your own account and use that to move forward.

### Throttle Handling
`python-amazon-mws` does not (yet) provide its own handling for [MWS throttling](http://docs.developer.amazonservices.com/en_US/dev_guide/DG_Throttling.html), so you will need to account for this yourself (for now).

Throttle responses, and most other error responses, will still show as a response 200, since a valid HTTP response came through from MWS. Thus, please do not rely on `response.response` for this need. Instead, `response.parsed` will contain an `Error` node, which itself may contain `Code` and `Message` nodes.

* `Code` is MWS's internal code for the error (for which I don't think they actually publish a table of possible codes, so 🤷‍♂️ )
* `Message` is a string with details of the error.

Specifically for throttled responses, you will see `reponse.parsed.Error.Code == "RequestThrottled"`. If you check for this case, you can implement a "back off" strategy similar to one suggested by MWS documentation, by retrying the response at set intervals with increasing duration (try again immediately, try again in a few seconds, then 5 seconds more, then 10 seconds more, etc.).

*As you can guess, I have some experience handling this, and I'll be looking to include some of my solutions in the near future.*

---

**Now then**, please let me know if you have any questions about specific use cases, and I'll be happy to help out. :)

**Comment by JasonCrowe** [comment]
Thank you for the detailed response. I found some of my issues solved with a pip --upgrade command. ;-)

This will help me begin to move forward & I appreciate the response.

**Comment by Bobspadger** [comment]
FYI Throttling returns a 503 error, not a 200.

Its also documented here:
http://docs.developer.amazonservices.com/en_US/dev_guide/DG_Errors.html


Error code | HTTP status code | Description
-- | -- | --
InputStreamDisconnected | 400 | There was an error reading the input stream.
InvalidParameterValue | 400 | An invalid parameter value was used, or the request size exceeded the maximum accepted size, or the request expired.
AccessDenied | 401 | Access was denied.
InvalidAccessKeyId | 403 | An invalid AWSAccessKeyId value was used.
SignatureDoesNotMatch | 403 | The signature used does not match the server's calculated signature value.
InvalidAddress | 404 | An invalid API section or operation value was used, or an invalid path was used.
InternalError | 500 | There was an internal service failure.
QuotaExceeded | 503 | The total number of requests in an hour was exceeded.
RequestThrottled | 503 | The frequency of requests was greater than allowed.

**Comment by GriceTurrble** [comment]
I was recalling that part from memory, and seemed to recall it was providing all responses as 200 if they came back from MWS at all. That may have changed, or I remembered wrong.

**Comment by Bobspadger** [comment]
it happens, I forget my name on a daily basis :)

**Comment by nateshmbhat** [comment]
i just came here to say "THANKS" :) You have made a fantastic work making this library . I hope amazon adopts this as their official API library :+1:  

Big thanks :+1:

**Comment by GriceTurrble** [comment]
Documentation is being overhauled and updated, coming in with #207 . Should clear up a lot of this once we get that documentation live in a public space.
