### ISSUE TITLE
enable deepcopy for DictWrapper

### ISSUE THREAD

**Issue by elcolumbio** [python-amazon-mws/python-amazon-mws#63]
i run into this because i want to dump the response object into a yaml file.

```
products_api = mws.Products()
products = products_api.get_x()
mydict = vars(products)  # same as products.__dict__
type(mydict['_response_dict'])

```
this returns
luigipipe.mws.mws.utils.ObjectDict

i think it should return: dict

A very simple approach for problems of that kind i found [here](https://www.peterbe.com/plog/must__deepcopy__).

If you think that is a good idea i can try to understand and fix this.

**Comment by GriceTurrble** [comment]
I haven't ignored this one, just been tossing it around in my head for a while.

I see no real issue offering that functionality, since it's unlikely to get in the way of other methods.

Note that in your pseudocode, `products` is an instance of `DictWrapper`, and that `parsed` attribute is a shorthand to `response_dict`.

Thus, `products.parsed` will result in an instance of `ObjectDict`, which is similar to the dict-like object in the example you've linked. That's the part where we'd add a `__deepcopy__` to enable this function.

---

I have a bit of bandwidth this weekend, so I'll play around with this stuff, see what we can work out. :)

**Comment by elcolumbio** [comment]
I try to understand how manipulated dictionaries or dict like classes from  scratch work.
It seem those problems are the price you pay for your class like dicts.
What i find striking is that everyone implements this different.
I am trying a lot of them out.
Opinions are: don't inherit from dict,that would break things like get(item , default) will return a dict and not a DotDict, it somehow isn't using your __getattr__ . Those people are using the collections module.

What's interesting with our ObjectDict it does not the heavy lifting of recursion. It takes as input only none nested dictionaries.
That have to change if we want to pass a nested dictionary once (like that we get from xmltodict).

**Comment by elcolumbio** [comment]
Like argued in the comment section of that link, the copy should work without a dunder deecopy method.
In my new version it does. Tough it's a bit inconvenient since vars returns the dict nested:
{'_DotDict__data': {'EndDate': '2018-05-29T04:24:10+00:00',
  'ReportProcessingStatus': '_SUBMITTED_',
  'ReportRequestId': '548585017',
  'ReportType': '_GET_FLAT_FILE_OPEN_LISTINGS_DATA_',
  'Scheduled': 'false',
  'StartDate': '2018-05-29T04:24:10+00:00',
  'SubmittedDate': '2018-05-29T04:24:10+00:00'}}
But all nested Dicts are Dicts and not DotDict objects.
