### ISSUE TITLE
mws.Orders().list_order_items()  can only get item info one order_id per time? 

### ISSUE THREAD

**Issue by archtaurus** [python-amazon-mws/python-amazon-mws#70]
This method called **list_order_items**, but its parameter **amazon_order_id** not accept a list of ids.
Is that so? Or how to get many items' information with all order_id I get from the **list_orders** method?

BTW, my english is badly good! sigh ...

**Comment by GriceTurrble** [comment]
According to [MWS documentation](http://docs.developer.amazonservices.com/en_US/orders-2013-09-01/Orders_ListOrderItems.html), this method is intended to return items for a single Order ID. In order to get the items for many orders at once, you would simply need to run the method for each order in succession.

**Comment by archtaurus** [comment]
Thanks for your reply :+1:
