### ISSUE TITLE
drop pyhon 2.7 support in 1.0 release

### ISSUE THREAD

**Issue by elcolumbio** [python-amazon-mws/python-amazon-mws#83]
- We are a small library, so we really should have a relentless focus on improving.
I just found an example dicussion in our upstream dependency [requests](
https://github.com/requests/requests/issues/4659).
An argument is in 18 month pyhon 2.7 is dead. Tests will start to break ...
But it will be way sooner, since our upstream dependencies will switch earlier.

We can release a stable 0.9 which people can use, if they like to use old software in the first place.

To support python 2.7 is already taking like 1/5 additional efforts, which could be better spent.

**Comment by SimoB** [comment]
Please don't!

**Comment by JasonCrowe** [comment]
I would agree that supporting python 3 should be the priority. Many projects have dropped 2.7 support already, and it only makes sense to continue 2.7 if additional effort isn't needed.

**Comment by Ldvt** [comment]
I use mws since two years. From a seller point of view some "core sense" features are still missing. From a coder point of view the library is improving. Personally I do not care if the project preferres to drop support for python 2.7 to move faster, however the mws library should be for the widest audience possible.

**Comment by GriceTurrble** [comment]
**Short version**: For the foreseeable future, we will continue to maintain support for Python 2.7.

**Longer**: maintaining our current support for 2.7-compatible code, in my opinion, is not that much of a hindrance on progress with `python-amazon-mws`. For downstream projects that continue to use 2.7 for various reasons, we can continue to support them at and beyond the 1.0 release, up until general 2.7 support has ceased in 2020.

20% effort in maintaining 2.7 compatibility seems like a stretch, but then again I have not been writing the majority of code recently (thank you kindly, contributors 👍 ).

In terms of what @elcolumbio mentioned:

* Yes, later versions of our dependencies may end up breaking our code if they update to drop Py2.7. That said, we can mitigate by properly declaring the versions of our dependencies to use, including min and max version numbers. If we know that requests 2.19 will break on Py2.7, then we must declare requests<2.19 as a dependency. This is standard practice, and one we must maintain.
* `requests`'s discussion on the issue specifically refers to Py2.6, which we do not support, anyway.
* Py2.7 dies in 18 months, which means we can support it for 18 months until the Python community at large is ready to update-or-die.

While it makes sense to push to support the latest and greatest of Python so we can take advantage of new tools as things improve, we should also endeavor to cover the widest possible audience. Some users, especially those developing for a company product, will need code that can support older versions of the language or even older versions of certain dependencies due to the slower adoption taken by larger firms. My own firm, for instance, maintains lists of technology and permitted versions of that tech, which will often lag behind the latest versions for 6 months as their own security team vets the new code or forks it themselves for internal use.

---

That all being said, there is a simpler answer: we do not have a full version of the library available yet. The next release we're planning introduces some breaking changes, which necessitates a major version number to avoid confusion, hence it will release at 1.0.

Beyond that release, future releases are less likely to introduce breaking changes as long as we start with a strong foundation, so I think it is possible for us to properly drop 2.7 support in a 1.1 or 1.2 release without causing too much trouble.

**Comment by elcolumbio** [comment]
I am not very educated. So i have some broad questions.
Where can i read about software lists in big companies?
I guess old software is often times a bigger security risk than new software.
Most software is continously released.
I might be very wrong, it just feels those companies could do that pre 2008, but that's 10 years due.
Other reasons like licensing would make more sense, but are not relevant here.

Ok actually i searched for some time and accenture seems to have quite strict rules.
Still they say: Be careful when using non-Accenture technology solutions or services.
From that paragraph it seems you could use this library in accenture if you have all the data on your systems and you need that data for a purpose. https://www.accenture.com/_acnmedia/PDF-63/Accenture-CoBE-Brochure-English.pdf

I can close that issue, i tried to understand why not. I don't get it.

**Comment by elcolumbio** [comment]
Why I brought this up. Like most python maintainer, or core developer i know. Print it in big letters that it is bad behavior to keep using python2 over python3.
We use requests they scream to your face dont use python2.
We are a small project. We have no downstream dependencies. Only the stuff everyone does on its own, which we should not care in this case.
I do understand if chardet gets used 90% by requests they have some duty to requests user. That's not the case here.

**Comment by elcolumbio** [comment]
Probably this high level discussion, which could be too opionated. We can quit for a moment. 
@Ldvt 
your comment "From a seller point of view some "core sense" features are still missing." is interesting.

There is an easy answer for that. Especially after @GriceTurrble splitted the mws.py in many api files.
So now we have a core, which includes files like mws.py and utils.py.
You should be able to copy the new api functionality and use it with an old core.
That is what people are doing all the time.

**Comment by elcolumbio** [comment]
Sorry. I deleted my off topic comments. Even the last post i summarize up here.

- I think 20% is low if you discount the linear? increase of issues and the removing of the clutter in 2020.
- new apis can be copy pasted to older mws versions.

We already put a lot of work into a 1.0 with support for pyhon2.7, so let's just go for it.
After the 1.0 we can start working for a 2.0 with pure python3.
