### ISSUE TITLE
HTTPError with certain number of items

### ISSUE THREAD

**Issue by RipcordBrands-ZK** [python-amazon-mws/python-amazon-mws#93]
Hello,

On several different function calls in the "InboundShipments" class (possibly present in other calls as well) I'm getting either a 502 Server Error or a 400 Client Error when trying to submit a request after there is a certain number of items, even if the number is far below the throttling limit.

For example, with the "UpdateInboundShipment" function, I have no problem submitting a request that contains something like 10-15 SKUs. However, if I try to submit a request that has more than about 30 SKUs, I consistently get one of the two above errors. According to the documentation this request can have up to 200 items so it doesn't seem to be related to throttling. Possibly something related to the URL length?

Anyone else experiencing this issue? I can divide up my SKUs into multiple calls to make it functional but I'm interested to know if this is a bug or if I'm just missing something and this is a part of the normal functionality. 

Thanks for your help

**Comment by GriceTurrble** [comment]
I have experienced this in the past, now I think about it. It is most likely URL length. I am not certain if this is something we can fix, or if there is some limitation to `requests` getting in the way.

**Comment by anssih** [comment]
The issue is that python-amazon-mws always sends the parameters in the query string, even for POST requests.

Per https://docs.developer.amazonservices.com/en_US/dev_guide/DG_ClientLibraries.html:

> Amazon MWS requires that the size of the HTTP request-line must be less than 8190 bytes and the size of the HTTP request body be less than 2048 MB.
> 
> If you are sending an HTTP request-line that exceeds the limit, then you must reduce your HTTP query parameters and use the HTTP request body parameters.

So for POST requests (or at least the large ones) python-amazon-mws should pass all the parameters (including `Signature`) in the body using `application/x-www-form-urlencoded` instead of the query string (except of course when body is already occupied by e.g. feed data for `SubmitData`).

**Comment by hazaard** [comment]
Hi. I'm having the same problem when i'm using put_transport_info method from InboundShipment (development branch) to put data about boxes. I had to implement this method because it's commented out in library but I'm pretty sure it's not related with my implementation but rather with request URL limit.
Issue appears when I have more than 6 boxes in shipment. URL becomes too long and Amazon raises 400 error without any meaningful details.
I see your comment here about not using POST request correctly:
https://github.com/python-amazon-mws/python-amazon-mws/blob/develop/mws/mws.py#L265

**Comment by GriceTurrble** [comment]
Yes, that's a problem, for sure. Once I've got the current sprint out of the way, that will be my next focus.

Ostensibly it should be an easy fix, but I don't have a seller account to do my own testing, so will require some coordination with those that do.

**Comment by hazaard** [comment]
Hey, thanks for the response! Let me know if you need some help with testing on the actual seller account. I won't be able to check all methods but plenty of them are used by me.
