### ISSUE TITLE
Is Amazon the seller

### ISSUE THREAD

**Issue by JasonCrowe** [python-amazon-mws/python-amazon-mws#99]
I found that I can detect the sales channel (FBM or FBA) in get_lowest_offer_listings_for_asin. 

Does anyone know where I can find if Amazon is the seller?

**Comment by Bobspadger** [comment]
I don't think they show you when you do an API call for the item.

They do show it when you use their SQS queues through subscriptions.

**Comment by Bobspadger** [comment]
The SQS queue does state if the seller is amazon or not.

It costs us about $2 a month to receive updates on 5000 products per month (about 2million messages)

This allows me to reprice within 2 minutes (the quickest you can send update back to amazon due to their throttling)

For the API calls, I did as @GriceTurrble has mentioned, which is I have a helper script that goes and pulls the rating count from our competitors, and matches this to the rating count returned in the API call.

I'd recommend looking at the subscriptions section of this.


I'll try to dig out an example response for you later today to show you what you get.

**Comment by Bobspadger** [comment]
https://www.amazon.co.uk/sp?_encoding=UTF8&asin=B011ITKLFU&isAmazonFulfilled=&isCBA=&marketplaceID=A1F83G8C2ARO7P&orderID=&seller=AZH2GF8Z5J95G&tab=&vasStoreID=

SellerID AZH2GF8Z5J95G

You have to do a bit of digging, but I just have my helper file that goes out, checks on the seller page by the seller ID, and stores this in the DB.

and then just look in the 

```xml
                <Offer>
                    <SellerId>A1O93PY9YZG2S0</SellerId>
                    <SubCondition>new</SubCondition>
                    <SellerFeedbackRating>
                        <SellerPositiveFeedbackRating>97</SellerPositiveFeedbackRating>
                        <FeedbackCount>46531</FeedbackCount>
                    </SellerFeedbackRating>
                    <ShippingTime minimumHours="24" maximumHours="48" availabilityType="NOW"/>
                    <ListingPrice>
                        <Amount>58.25</Amount>
                        <CurrencyCode>GBP</CurrencyCode>
                    </ListingPrice>
                    <Shipping>
                        <Amount>0.00</Amount>
                        <CurrencyCode>GBP</CurrencyCode>
                    </Shipping>
                    <ShipsFrom>
                        <Country>GB</Country>
                        <State></State>
                    </ShipsFrom>
                    <IsFulfilledByAmazon>false</IsFulfilledByAmazon>
                    <IsBuyBoxWinner>false</IsBuyBoxWinner>
                    <PrimeInformation>
                        <IsPrime>false</IsPrime>
                        <IsNationalPrime>false</IsNationalPrime>
                    </PrimeInformation>
                    <IsFeaturedMerchant>true</IsFeaturedMerchant>
                    <ShipsDomestically>true</ShipsDomestically>
                </Offer>
```

They will also state `IsFullfilledByAmazon = true`

**Comment by Bobspadger** [comment]
@JasonCrowe can we consider this one done?
